menu:
    Blog: /
    Archive: /archives/
    About: /about
    GitHub: https://github.com/GraphiCon
    知乎专栏: https://zhuanlan.zhihu.com/graphicon
    Rss: /atom.xml


favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: graphicon-io
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
